### ISSUE TITLE
no module named 'chromadb'

### ISSUE THREAD

**Issue by krissi15** [douglasmakey/chatting-with-docs#2]
Hello Douglas, 
I'm having an issue running the program. When I type 'python main.py app' into the console, I get 'ModuleNotFoundError: No module named 'chromadb'.' I've tried a few things but can't seem to find the problem. Could you please help me with this?

Kind regards 
Kristof

**Comment by douglasmakey** [comment]
Hi @krissi15 , did you install the dependencies? You should run `pip install -r requirements.txt`

**Comment by krissi15** [comment]
Hello, I first navigate to the "chatting-with-docs" directory, then I execute the command "pip install -r requirements.txt," and after that, I attempt to start the application with "python main.py app" or try "python main.py scraping --target bg3 --output-dir "docs/bg3"," but neither of these works.

**Comment by douglasmakey** [comment]
Weird, everything is working fine for me so far.

```bash
$ git clone git@github.com:douglasmakey/chatting-with-docs.git && cd chatting-with-docs
$ python3 -m venv .venv && source .venv/bin/activate
$ pip install -r requirements.txt
$ python main.py app
```
